### PR TITLE
Fixed bug on shortcut commands for overrides 

### LINKED ISSUE #1165: Feed/Spindle speed override shortcuts do not function when code is being sent
#### Version
  UGS Platform 2.0 - Nightly Build 

#### Operating system
  Windows 7

#### Platform
  GRBL 1.1f

### PR DESCRIPTION
**Pull request by breiler**
Fixed bug where shortcut commands for overrides couldn't be executed when machine was running.  Also checks the controller for real time override support.

Fixes #1165

### CODE REVIEW

File: ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/services/OverrideActionService.java [hunk 1]
```diff
@@ -56,47 +55,42 @@ public void runAction(Overrides action) {
         }
     }
 
-    public boolean canRunCommand() {
-        return backend.getControlState() == UGSEvent.ControlState.COMM_IDLE;
+    public boolean canRunAction() {
+        return backend.isConnected() && backend.getController().getCapabilities().hasOverrides();
```
Comment (winder) [inline ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/services/OverrideActionService.java]: Wow! What a huge oversight. Thanks for finding this.
